config/routes.rb
Rails.application.routes.draw do
  resources :traceable_records

  root 'traceable_records#index'

  resources :traceable_records do
    collection do
      post :import
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trace_record.rb
class TraceRecord < ApplicationRecord
  mount_uploader :file, AvatarUploader
end

app/models/traceable_record.rb
class TraceableRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trace_records_controller.rb
class TraceRecordsController < ApplicationController

	def create
		
		@trace_record = TraceRecord.create(permitted_params)
		byebug
		column_names = data['Workbook']['Worksheet']['Table']['Row'][0]['Cell'].collect{|a| a['Data'].gsub(' ', '_').gsub('-', '').downcase}
		ActiveRecord::Base.connection.create_table :traceable_records do |t|
			column_names.each do |column_name|
		    t.string column_name
		    t.text :body
		  end
		redirect_to root_path
	end

	def permitted_params
		params.require(:trace_record).permit!
	end

end

app/controllers/traceable_records_controller.rb
class TraceableRecordsController < ApplicationController
  before_action :set_traceable_record, only: [:show, :edit, :update, :destroy]

  # GET /traceable_records
  # GET /traceable_records.json
  def index
    @traceable_records = TraceableRecord.all
  end

  # GET /traceable_records/1
  # GET /traceable_records/1.json
  def show
  end

  # GET /traceable_records/new
  def new
    @traceable_record = TraceableRecord.new
  end

  # GET /traceable_records/1/edit
  def edit
  end

  # POST /traceable_records
  # POST /traceable_records.json
  def create
    @traceable_record = TraceableRecord.new(traceable_record_params)

    respond_to do |format|
      if @traceable_record.save
        format.html { redirect_to @traceable_record, notice: 'Traceable record was successfully created.' }
        format.json { render :show, status: :created, location: @traceable_record }
      else
        format.html { render :new }
        format.json { render json: @traceable_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traceable_records/1
  # PATCH/PUT /traceable_records/1.json
  def update
    respond_to do |format|
      if @traceable_record.update(traceable_record_params)
        format.html { redirect_to @traceable_record, notice: 'Traceable record was successfully updated.' }
        format.json { render :show, status: :ok, location: @traceable_record }
      else
        format.html { render :edit }
        format.json { render json: @traceable_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traceable_records/1
  # DELETE /traceable_records/1.json
  def destroy
    @traceable_record.destroy
    respond_to do |format|
      format.html { redirect_to traceable_records_url, notice: 'Traceable record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    @trace_record = TraceRecord.create(import_params)
    xml = File.open(@trace_record.file.path)
    data = Hash.from_xml(xml)
    rows = data['Workbook']['Worksheet']['Table']['Row']
    rows.each do |row|
      next if (rows[0] == row) || row['Cell'].count != 12
      values = row['Cell'].collect{|a| a['Data']}
      traceable_record = TraceableRecord.new
      columns.each_with_index do |column, index|
        traceable_record.send("#{column}=",values[index])
      end
      traceable_record.file_name =  @trace_record.file.filename
      traceable_record.file_upload_date = Date.today.to_s
      traceable_record.save
    end
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traceable_record
      @traceable_record = TraceableRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traceable_record_params
      params.require(:traceable_record).permit(:custom_id, :sales_order, :customer, :item, :description, :date_shipped, :mfg_number, :mfg_serial_number, :commas1_id, :installed_software_version, :sim_id, :ip_address)
    end

    def columns
      ['custom_id', 'sales_order', 'customer', 'item', 'description', 'date_shipped', 'mfg_number', 'mfg_serial_number', 'commas1_id', 'installed_software_version', 'sim_id', 'ip_address']
    end

    def import_params
      params.require(:trace_record).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trace_records_helper.rb
module TraceRecordsHelper
end

app/helpers/traceable_records_helper.rb
module TraceableRecordsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<%= form_for TraceRecord.new do |f|%>
		<%= f.file_field :file%>
		<%= f.submit 'import'%>
	<%end%>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/traceable_records/_form.html.erb
<%= form_for(@traceable_record) do |f| %>
  <% if @traceable_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@traceable_record.errors.count, "error") %> prohibited this traceable_record from being saved:</h2>

      <ul>
      <% @traceable_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Custom ID' %><br>
    <%= f.text_field :custom_id %>
  </div>
  <div class="field">
    <%= f.label :sales_order %><br>
    <%= f.text_field :sales_order %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :date_shipped %><br>
    <%= f.text_field :date_shipped %>
  </div>
  <div class="field">
    <%= f.label :mfg_number %><br>
    <%= f.text_field :mfg_number %>
  </div>
  <div class="field">
    <%= f.label :mfg_serial_number %><br>
    <%= f.text_field :mfg_serial_number %>
  </div>
  <div class="field">
    <%= f.label :commas1_id %><br>
    <%= f.text_field :commas1_id %>
  </div>
  <div class="field">
    <%= f.label :installed_software_version %><br>
    <%= f.text_field :installed_software_version %>
  </div>
  <div class="field">
    <%= f.label :sim_id %><br>
    <%= f.text_field :sim_id %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traceable_records/edit.html.erb
<h1>Editing Traceable Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @traceable_record %> |
<%= link_to 'Back', traceable_records_path %>

app/views/traceable_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Traceable Records</h1>

<table>
  <thead>
    <tr>
      <th>Custom</th>
      <th>Sales order</th>
      <th>Customer</th>
      <th>Item</th>
      <th>Description</th>
      <th>Date shipped</th>
      <th>Mfg number</th>
      <th>Mfg serial number</th>
      <th>Commas1 id</th>
      <th>Installed software version</th>
      <th>Sim id</th>
      <th>Ip address</th>
      <th>File Name</th>
      <th>File Upload Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traceable_records.each do |traceable_record| %>
      <tr>
        <td><%= traceable_record.custom_id %></td>
        <td><%= traceable_record.sales_order %></td>
        <td><%= traceable_record.customer %></td>
        <td><%= traceable_record.item %></td>
        <td><%= traceable_record.description %></td>
        <td><%= traceable_record.date_shipped %></td>
        <td><%= traceable_record.mfg_number %></td>
        <td><%= traceable_record.mfg_serial_number %></td>
        <td><%= traceable_record.commas1_id %></td>
        <td><%= traceable_record.installed_software_version %></td>
        <td><%= traceable_record.sim_id %></td>
        <td><%= traceable_record.ip_address %></td>
        <td><%= traceable_record.file_name %></td>
        <td><%= traceable_record.file_upload_date %></td>
        <td><%= link_to 'Show', traceable_record %></td>
        <td><%= link_to 'Edit', edit_traceable_record_path(traceable_record) %></td>
        <td><%= link_to 'Destroy', traceable_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Traceable record', new_traceable_record_path %>


<%= form_for TraceRecord.new, {url: import_traceable_records_path} do |f|%>
    <%= f.file_field :file%>
    <%= f.submit 'import'%>
  <%end%>

app/views/traceable_records/new.html.erb
<h1>New Traceable Record</h1>

<%= render 'form' %>

<%= link_to 'Back', traceable_records_path %>

app/views/traceable_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Custom ID:</strong>
  <%= @traceable_record.custom_id %>
</p>

<p>
  <strong>Sales order:</strong>
  <%= @traceable_record.sales_order %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @traceable_record.customer %>
</p>

<p>
  <strong>Item:</strong>
  <%= @traceable_record.item %>
</p>

<p>
  <strong>Description:</strong>
  <%= @traceable_record.description %>
</p>

<p>
  <strong>Date shipped:</strong>
  <%= @traceable_record.date_shipped %>
</p>

<p>
  <strong>Mfg number:</strong>
  <%= @traceable_record.mfg_number %>
</p>

<p>
  <strong>Mfg serial number:</strong>
  <%= @traceable_record.mfg_serial_number %>
</p>

<p>
  <strong>Commas1 id:</strong>
  <%= @traceable_record.commas1_id %>
</p>

<p>
  <strong>Installed software version:</strong>
  <%= @traceable_record.installed_software_version %>
</p>

<p>
  <strong>Sim id:</strong>
  <%= @traceable_record.sim_id %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @traceable_record.ip_address %>
</p>
<p>
  <strong>File Name:</strong>
  <%= @traceable_record.file_name %>
</p>
<p>
  <strong>File Upload Date:</strong>
  <%= @traceable_record.file_upload_date %>
</p>

<%= link_to 'Edit', edit_traceable_record_path(@traceable_record) %> |
<%= link_to 'Back', traceable_records_path %>